### ISSUE TITLE
Letterboxd external ratings from IMDb and Metacritic don't work anymore.

### ISSUE THREAD

**Issue by thomasdingemanse** [rcalderong/userscripts#1]
I've tried fixing this myself and I thought maybe you could also use these changes to fix the problem for other users. The root of the problem is that IMDb's source code has changed, so the Elements which had the ratings in them could not be found. All my edits are within the function **getIMDbAndMetaRatings()**.

I changed the following variables/lines of code:

Set **ratingsElt** to _#title-overview-widget_ instead of _#overview-top_:
`ratingsElt = dom.getElementById("title-overview-widget");`
Set **imdbRatingElt** to the correct element (the one with _itemprop=ratingValue_):
`imdbRatingElt = ratingsElt.querySelector("[itemprop=ratingValue]");`
Removed the **MetaRatingMatch** code and grabbed the Metascore value directly from the right element on the IMDb title page (_.metacriticScore span_). If the element exists, its value is parsed in the same way as the IMDb rating. removed the line where **var metaRating** is created, because it has already been created before. Then just update the ratings on Letterboxd (including the right metacritic URL) just as it was in the old code:

```
    function getMetaRating() {
        var metaRating,
            metaRatingElt = ratingsElt.querySelector(".metacriticScore span");

        if (metaRatingElt) {
            metaRating = parseFloat(metaRatingElt.textContent);
            GM_xmlhttpRequest({
                method: "GET",
                url: imdbUrl + "criticreviews", // Metacritic reviews page on IMDb
                onload: function (res) {
                    var pageContent,
                        metaUrl;

                    dom = parser.parseFromString(res.responseText, "text/html");
                    pageContent = dom.getElementById("main").innerHTML;
                    metaUrl = pageContent.
                        match(/<a.*href="(.*?)".*>See all \d+ reviews/)[1];

                    updateRatingData("Metascore", metaRating,
                        metaRating / 10, metaUrl);
                }
            });
        } else {
            updateRatingData("Metascore", null);
        }    
    }

    if (ratingsElt) {
        getIMDbRating();
        getMetaRating();
    } else {
        updateRatingData("IMDb", null);
        updateRatingData("Metascore", null);
    }
}
```

I think the script didn't work anymore because IMDb made changes to their DOM. If you want to use these changes I made, you can of course do so and you can change/add/remove anything you want. I tested it and it works for me, at least.

**Comment by soyguijarro** [comment]
Hey Thomas, thanks a lot for reporting this and taking the time to fix the problem. I don't use these scripts myself anymore so I didn't notice the issue. I'll try to test the changes you suggest and release a fix as soon as possible.
